[phases.setup]
nixPkgs = ["...", "freetype", "fontconfig", "dejavu_fonts"]

[phases.build]
cmds = ["chmod +x mvnw && ./mvnw clean install -DskipTests", "mkdir -p /usr/lib && ln -s /nix/store/*/lib/libfreetype.so.6 /usr/lib/libfreetype.so.6 || true"]